### PR TITLE
HW cat-walk

### PR DESCRIPTION
**Pull request by danielmoi**
1. difficulty: 8
2. struggles: I initially tried to create a moving-gif factory function, but I needed to access the cat's left property, so I could attach mario relative to that. It became too difficult :( so there's a lot of functions...
3. more-info: I would love to know how to refactor my code for this HW better
4. time: 4+ hours

### CODE REVIEW

**Comment by danielmoi** [comment]
Calculator Ruby
1. difficulty: 7
2. struggles: found it difficult to limit the size of my functions
3. more info: is there a way around the "floating point" errors? like 0.1 + 0.2 != 0.3
4. time: ~3 hrs

**Comment by danielmoi** [comment]
HW 04 Tues MTA
1. Difficulty: 8
2. Struggles: it was tricky getting my head around Ruby syntax. discovering some awesome array functions in Ruby though!
3. More info: all good. getting my head around the Ruby documentation.
4. time ~ 3 hrs

**Comment by danielmoi** [comment]
HW 04 Wed Movie DB
1. Difficulty: 9
2. Struggles: difficult making the routes work properly, finally figured it out
3. More info: the code-along on Thurs helped a lot.
4. Time: ~ 5 hrs

**Comment by danielmoi** [comment]
HW 04 Thu Pokemon DB
1. Difficulty: 8
2. Struggles: a bit easier, especially because of the butterfly code-along. Refactored some of the code to make more intuitive sense to myself
3. More info: looking forward to Active Record and Rails! And being able to deploy onto a remote server!
4. Time ~ 5 hrs

**Comment by danielmoi** [comment]
HW W4 Fri Pokemon Active Record
1. Difficulty: 5
2. Struggles: I found this fairly straightfoward – the code along in class helped immensely.
3. More info: all good
4. Time ~ 3 hrs

**Comment by cjbarnaby** [comment]
Hey Daniel, 

Sorry for the delay in getting feedback to you. I'll try to get the whole lot done today, but for now...

## Cat Walk

+1000 points for spinning nyan cat. All works perfectly and the code looks great - in terms of refactoring, there are a few things you could do. Obviously this would all have been a lot easier with jQuery, but I'll limit the feedback to what you could have done with vanilla JS. Re: getting the cat's position to place mario - you could have maybe called a `var placeMario = function(left) {}` function passing in the position of the cat to append mario to the body initially. A few things that could have DRYd up the code a little:

### A 'showElement' function called by setTimeouts for each image

This isn't going to save you anything in terms of lines of code or performance, and wouldn't really save you any time writing your code initially, but it would make it a little easier to change your code down the line: 

```
var showElement = function(name) {
  name.style.display = 'block';
};

setTimeout(function() {
  showElement(mario);
}, 1000);
```

### A 'creator' function for each image

Since you're pretty much doing the same set of actions for each element, I'd maybe have thought about setting up a function for styling and appending the images, and appending the element to the body _last_

```
var creator = function(element, image, position, width, top, left, display) {
  var style =
    'position: ' + position + ';' +
    'width: ' + width + 'px;' +
    'top: ' + top + 'px;' +
    'left: ' + left + 'px;' +
    'display: ' + display + ';' ;
  element.src = image;
  element.setAttribute('style', style);
  document.body.appendChild(element);
};

var mario = document.createElement('img');
creator(mario, 'img/mario2.gif', 'absolute', '160px', '0', '10', 'none');

```

This wouldn't just reduce the amount of code, but should _generally_ also improve performance by reducing the number of reflows and repaints (see [this article](https://dev.opera.com/articles/efficient-javascript/?page=3#reflow) ). I say 'generally' because there are a few things at play here (which could mean that you might not necessarily get any performance gains - for example, if you manipulate an element before it is appending to the body, or while it's visibility is set to 'none' or it's position is 'absolute', there is no reflow or repaint.

**Comment by cjbarnaby** [comment]
## Calculator Ruby

All looks great. Clean code, good separation of functions and clear comments. One thing you could have done is change the input fields to type="number", which would prevent people from entering non-numerical characters, but really, you'd still want to have your validate function (since people could still force a non-numerical character in there). 

Re: precision with floats in JS, it depends on the context. Sometimes .toFixed(x) (where x is the decimal place precision you need) might be enough, but it returns a string representation of the float (same with .toPrecision(), but . Still, that might be enough for things like basic currency calculations. Otherwise, there are libraries like [bignumber.js](https://github.com/MikeMcl/bignumber.js) and [bigdecimal](https://github.com/dtrebbien/BigDecimal.js) that give you something approximating real mathematical precision (apparently). 

JT's pretty big on numbers and maths, so he might be a good person to speak to about that.

**Comment by danielmoi** [comment]
Thanks for the feedback chris.
Much appreciated.

**Pull request merged**
