### PR TITLE
Homework to-date

### PR DESCRIPTION
**Pull request by samanthaDiamond**

### CODE REVIEW

**Comment by samanthaDiamond** [comment]
In general I am initially totally confused about the content and concepts but after I go over it myself and with you I have a much better understanding. I really appreciate you taking the time to explain things to me (sometimes multiple times). You're extremely patient!

**Comment by samanthaDiamond** [comment]
**How difficult did you find this (out of 10)? *_5-6/10
*_Was there anything that you struggled with?** Yes, using some of the helpers and css styling. 
**Is there anything that you'd like some further information on?** I think I just need to keep practicing and reading rail guides. 
*_Roughly, how long did it take? *_ ~7 hours each night

**Comment by samanthaDiamond** [comment]
I've found all the homework REALLY hard. I'm spending about 7 hours on average each night trying to work through it. I feel that I'm not where I should be at this stage of the course but I'm hoping it all clicks soon!

**Comment by samanthaDiamond** [comment]
Difficulty: 8/10
Firstly underscore is awesome! I just need to practice using the underscore methods.
Backbone on the other hand is very confusing. I think I understand what is happening from a higher level and can definitely see why it's a great tool (framework). However, I don't find it to be overly intuitive and this makes it hard for me to understand what is happening at a closer level. The main thing I'm struggling with at the moment is understand how the front and back-end fit together. There are front and back-end routes and views and I'm not sure why? I also don't feel confident about what to include in the front vs back-end routes/views.

**Comment by cjbarnaby** [comment]
Hey Samantha, 

Sorry it's taken me a long time to get round to this. Looking at the things you've been struggling with, come and grab me and we can go over Ajax; Jack's probably a better port of call for Backbone help, but I'm always happy to try and help in anyway I can (I can handle the Backbone/Rails interface, at least, as well as why there are back & front end routes and views, etc).

**Comment by samanthaDiamond** [comment]
Thanks Badger! I'll grab you sometime over the next week to have a chat
about things I'm struggling with :-)

**Pull request merged**
