### PR TITLE
Ruby Day One Homework

### PR DESCRIPTION
**Pull request by joshpanebianco**
Hi,

I managed to get the first 4 functions working + - \* and /.

Thanks for all your help badger.

### CODE REVIEW

**Comment by joshpanebianco** [comment]
Hey Jack,

I did what you asked and did the Pseudocode first.

I also did a lot of googling and posted my code on slack.

In the end I couldn't get my head around how the loop works in ruby vs JS.

**Comment by joshpanebianco** [comment]
Hey Jack,

Last night I started with the Pseudocode first and was able to get it up where the page generated HTML but the result showed back nothing.

But with Joel's help I was able to get the search function working.

I also did work with the css to get the file looking nice.

**Comment by joshpanebianco** [comment]
Hey Jack,

I tried to get copy the example from class last night but that did not really work.

I think I did ok to get it halfway.

My css skills are getting better.

**Comment by joshpanebianco** [comment]
Hey,

For this homework I didn't focus on css I just focused on trying to get the functions working.

I did manage to get the first one working but for the second one I could not figure out the IF statements in ruby.

**Comment by joshpanebianco** [comment]
Hey,

Last night I felt like I was making progress.

I am getting my head around rails and also I am getting better at making the front end look good.

**Comment by joshpanebianco** [comment]
Hey,
I was following the steps from the class notes on slack. I did get to the last step. I Think its like 90% done.
Let me know what you think.

**Comment by joshpanebianco** [comment]
Hey Mate,

This is what I got to with the homework. Maybe we can talk in the break to help get it working.

**Comment by joshpanebianco** [comment]
Hi,
I got the youtube API working as I wanted. Very happy with.
Today was a win.

**Comment by joshpanebianco** [comment]
Hi,
I got the endless scrolling to work.

I also got the images to display better, with spacing etc which was a css change not a change in the data feed.

**Comment by joshpanebianco** [comment]
Hi,
I really struggled with when the homework last night. Which sucks because I had some good days this week especially with the API stuff. 

I find the docs on the underscore site very hard to read.

I would love a review session on underscore.

**Comment by joshpanebianco** [comment]
Hi,
I find the backbone book very hard to read. So I also did the lynda Backbone course which helped me get a better understanding of it. I can see why backbone is help useful. I just need to get more practice with it.

**Comment by cjbarnaby** [comment]
Hey Josh, 

A few comments on your more recent homework:

### Movies

You were really close with this. Just a couple of things caught you up:
1. You were never calling the `getMovie()` function because your event handler was waiting for the button to be submitted (which doesn't mean anything). You needed to delegate that to the `$('form')` element, rather than `$('button')`. So, your event handler needed to be:

``` js
$('form').on('submit', getMovie);
```
1. I imagine that's what stopped you from progressing further, but basically all you needed to do was save whatever you wanted in the JSON object returned by the request in variables (where you had your console logs in your main.js) and append them to the DOM in the appropriate tags. So, for title, you just needed to go:

``` js
var title = info['Title'];
$('#results').append('<p>' + title + '</p>')
```

But that was basically it. Let me know if you have any other questions about this one.

###Flickr 

Nice work getting that one out - it wasn't easy!

###Underscore

I agree that the Underscore docs can be difficult to understand (they've got a lot of extra stuff in there) - the [Underscore Notes](https://ga-wolf.gitbooks.io/wdi13/content/week_07/wk07_day04.html) in GitBook might be a better starting point. I'm happy to go over some of the Underscore methods with you (you'll find that all the underscore methods we use frequently have a corresponding Ruby method - one important difference is that because there is no implicit return in JS, we often have to, for example, return the result of a block of code back to the function itself - eg _.reduce. 

###Backbone

Backbone's a _lot_ to get your head around in a couple of days - glad you found the Lynda guide helpful (I agree that the Todo app and accompanying documentation isn't perfect - skips over a lot of pretty important stuff). Again, for fundamentals, I'd suggest checking out the GitBook notes on it. Either way, you'll probably get a lot more familiar w/ Backbone over the next few days. 

Chris

**Pull request merged**
