### PR TITLE
Week_04 Day 1 Ruby Homework

### PR DESCRIPTION
**Pull request by danbennetts**
Difficulty: 5

I found learning Ruby to be quite exciting and fresh, still have a struggle a bit about writing pseudo code. I found it quite fun to do this homework even though I had done something similar with JS.

All in all was a good experience to get me introduced to Ruby.

I do need to brush up on conditionals and arrays/objects as I am still finding this to be quite a challenge.

### CODE REVIEW

**Comment by danbennetts** [comment]
Difficulty: 3

This one was pretty straight forward, had a bit of trouble but managed to get it sorted.

**Comment by danbennetts** [comment]
Movie Database
Difficulty: 6

This one was pretty cool to do actually, I love movies and creating a website which gets info is fun. I found this a little bit challenging but I got through it with a bit of help from Jack. 

I think I just need to read up on the documentation from Sinatra.

**Comment by danbennetts** [comment]
Difficulty 7

I have added a little database I created for Video Games using active record. I found this to be much easier than SQL. I still need to add CSS to the web app though, which I can do when I have the time this week.

I found this to be one of the more fun exercises. Just need help still with accessing arrays, objects/hashes. Conditionals are coming a little bit clearer to me now but still need to brush up on them.

This is has been a pretty busy week for me, and quite full on. But nothing I can't manage.

**Comment by danbennetts** [comment]
I have added quite alot of homework since week 4 I think.

This is all of it.

**Comment by danbennetts** [comment]
I have committed quite alot of homework in this request. From week 4 I think? This is all of it.

**Comment by cjbarnaby** [comment]
Hey Daniel, 

Just catching up on the homework - looks like you're on top of everything. I'm going to be checking homework PRs daily now, but will only be commenting specifically on code/issues if they're raised in each Pull Request, otherwise I'll just be having a quick look over the code, so just bring anything (no matter how big or small) to my attention in the PR. 

Cheers, 

Chris.

**Pull request merged**
