### PR TITLE
Weekend homework - ga bank

### PR DESCRIPTION
**Pull request by jennmawhinney**
I found this quite hard (7 out of 10).
I struggled with setting out the logic and in hindsight should probably have used functions inside objects.
It took around 24 hours (in between code school).

### CODE REVIEW

**Comment by jennmawhinney** [comment]
The database homework was fairly easy as it was mostly just copying and rejigging. I am having an issue displaying my thumbnail images in cakes_show.erb. I'm not

**Comment by jennmawhinney** [comment]
Sorry! Hit enter too quickly...following on from above:

I'm not quite sure how to fix this error. Any help would be awesome :-)

**Comment by jennmawhinney** [comment]
I updated my Cake Appreciation Society page using Active Record. Still trying to get my head around it!
It was quite easy as I had the butterflies project to refer to but I definitely couldn't have done it without that :-)

**Comment by jennmawhinney** [comment]
I really struggled with the styling of the button vs a link. This was explained this morning during demos so I will try and fix that up next time.

**Comment by jennmawhinney** [comment]
I did this in the dumbest way possible but I got it fully working! It was much clearer today after going through it today in class but it would be great to get some more info on callback functions...still trying to wrap my head around those :-)

**Comment by cjbarnaby** [comment]
Hey Jenn, 

Sorry I'm so far behind on giving you feedback on your homework. Can you come and speak to me if you want to chat about:
- Why your Cake app thumbnails weren't working;
- Callbacks.

Callbacks can be tricky one to get your head around, but the basic concept can be summed up as follows: a callback function is any function passed to another function as an argument, and then called within that function. Example: 

``` js

var someFunction = function(callback) {
  callback();
};

var ourCallBackFunction = function() {
  //Do stuff
}
```

In the example above, `ourCallBackfunction` is a callback function, which we call with `someFunction(ourCallBackFunction)` (which is called a _'higher order function'_) - we're passing the function `ourCallBackFunction` as an argument to the `someFunction`, which accepts a function as an argument (the parameter `callback`) and then executes that function (`callback()`).

That seems pretty boring, right? It gets crazy (and, unfortunately, more complicated) when you have functions that accept multiple arguments (not just the callback). Example:

``` js
var students = ["Jenn", "Sam", "Rany"];

var each = function(a, callback) {
//This function takes two arguments - an array and a callback function. 'Callback' is not a magic JS keyword - you could name that parameter whatever you liked, provided you used the same name to call the function in the block.
  for (var i = 0; i < a.length; i++) {
//Call the 'callback()' function for each element in the array, passing in the element itself
    callback(a[i]);
  }
};

var sayHey = function(name) {
  console.log("Hey " + name);
};

each(students, sayHey);
```

[Here are](http://www.sitepoint.com/demystifying-javascript-closures-callbacks-iifes/) a few [pretty good](http://javascriptissexy.com/understand-javascript-callback-functions-and-use-them/) article on callbacks.

Chris

**Pull request merged**
